name: autoupdate

on:
  workflow_dispatch:
  schedule:
  - cron: '15 0 * * 4'

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.BOT }}
    - name: Check Latest Version
      run: |
        pip3 install in_place
        python autoupdate.py
        git config --global user.name 'pinximei'
        git config --global user.email 'meipinxi22@163.com'
        git commit -am "Automate" || echo "nothing to update"
        git push
